routes/admin.php
<?php

// use Illuminate\Support\Facades\Route;

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::view("/test", 'test' );
Route::view('/sertifikat', 'user.sertifikat');
    Route::view('/', 'landing')->middleware("guest");
Route::group(['namespace' => "User\Auth", "middleware" => "guest", "as" => "user."], function () {
    Route::get("/login", "AuthController@showLogin")->name("login");
    Route::post("/login", "AuthController@login")->name("login.proses");
    Route::get("/register", "AuthController@showRegister")->name("register");
    Route::post("/register", "AuthController@register")->name("register.proses");
});

Route::group(['namespace' => "User", "middleware" => "auth:web", "as" => "user."], function () {
    Route::get("/logout", "Auth\AuthController@logout")->name("logout");
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");
    /**
     * Route User Course
     */
    Route::get("/course", "CourseController@index")->name("course.index");
    Route::get("/course/{courseId}", "CourseController@show")->name("course.show");
    Route::get("/course/{courseId}/done", "CourseController@updateCourseIsDone")->name("course.done");

    /**
     *  Route for Quiz
     */
    Route::get("/course/{courseId}/quiz/", "QuizController@index")->name("quiz.index");
    Route::post("/course/{courseId}/quiz/submit", "QuizController@submit")->name("quiz.submit");

    /**
     *  Route for Mission
     */

    Route::get("/mission", "MissionController@index")->name("mission.index");
    Route::get("/mission/{id}", "MissionController@show")->name("mission.show");
    Route::post("/mission/success", "MissionController@takeMission")->name("mission.take");

    Route::get("/leaderboard", "LeaderboardController@index")->name("leaderboard.index");
    Route::get("/certificate", "DashboardController@certificate")->name('certificate');
});




/**
 * This is route for admin page
 */
Route::redirect('admin', 'admin/dashboard');
Route::prefix('admin')->group(function () {
    Route::group(['namespace' => "Admin\Auth", "middleware" => "guest:admin", "as" => "admin."], function () {
        Route::get("/login", "AuthController@showLogin")->name("login");
        Route::post("/login", "AuthController@login")->name("login.proses");
        Route::get("/register", "AuthController@showRegister")->name("register");
        Route::post("/register", "AuthController@register")->name("register.proses");
    });

    Route::group(['namespace' => "Admin", "middleware" => "auth:admin", "as" => "admin."], function () {
        Route::get("/logout", "Auth\AuthController@logout")->name("logout");
        Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

        /**
         * Route Courses Page
         */
        Route::get("/course", "CourseController@index")->name("course.index");
        Route::get("/course/create", "CourseController@create")->name("course.create");
        Route::post("/course/store", "CourseController@store")->name("course.store");
        Route::get("/course/{id}/show", "CourseController@show")->name("course.show");
        Route::get("/course/{id}/edit", "CourseController@edit")->name("course.edit");
        Route::post("/course/{id}/update", "CourseController@update")->name("course.update");
        Route::get("/course/{id}/delete", "CourseController@delete")->name("course.delete");

        /**
         * Route for Stage
         */
        Route::get("/course/stage/create/{course_id}", "StageController@create")->name("stage.create");
        Route::post("/course/stage/store", "StageController@store")->name("stage.store");
        Route::get("/course/stage/{id}/edit", "StageController@edit")->name("stage.edit");
        Route::post("/course/stage/{id}/update", "StageController@update")->name("stage.update");
        Route::get("/course/stage/{id}/delete", "StageController@delete")->name("stage.delete");

        /**
         * Route for Quiz
         */
        Route::get("/course/quiz/create/{course_id}", "QuizController@create")->name("quiz.create");
        Route::post("/course/quiz/store", "QuizController@store")->name("quiz.store");
        Route::get("/course/quiz/{id}/edit", "QuizController@edit")->name("quiz.edit");
        Route::post("/course/quiz/{id}/update", "QuizController@update")->name("quiz.update");
        Route::get("/course/quiz/{id}/delete", "QuizController@delete")->name("quiz.delete");

        /**
         * Route for Mission
         */
        Route::get("/mission", "MissionController@index")->name("mission.index");
        Route::get("/mission/create", "MissionController@create")->name("mission.create");
        Route::post("/mission/store", "MissionController@store")->name("mission.store");
        Route::get("/mission/{id}/edit", "MissionController@edit")->name("mission.edit");
        Route::post("/mission/{id}/update", "MissionController@update")->name("mission.update");
        Route::get("/mission/{id}/delete", "MissionController@delete")->name("mission.delete");
        Route::get("/mission/{id}/show", "MissionController@show")->name("mission.show");
    });
});

/**
 *  Route for image upload
 */

app/Models/Stage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Stage extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/Admin/StageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Stage\StageStoreRequest;
use App\Http\Requests\Admin\Stage\StageUpdateRequest;
use App\Models\Stage;
use Illuminate\Http\Request;

class StageController extends BaseAdminController
{
    public function create($course_id)
    {
        return view("admin.stage.insert", compact('course_id'));
    }

    public function store(StageStoreRequest $request)
    {
        $data = Stage::create($data->except("files"));
        $this->setNotifyMessage("success", "Crate data success!");
        return redirect()->route("admin.course.show", ['id' => $request->course_id]);
    }

    public function edit($id)
    {
        $stage = Stage::find($id);
        return view("admin.stage.update", compact('stage'));
    }

    public function update(StageUpdateRequest $request, $id)
    {
        $stage = Stage::find($id)->update($request->except('files'));
        $this->setNotifyMessage("success", "Update data success!");
        return redirect()->route("admin.course.show", ['id' => $request->course_id]);
    }

    public function delete($id)
    {
        $stage = Stage::find($id)->delete();
        $this->setNotifyMessage("success", "Delete data success!");
        return redirect()->back();
    }
}

resources/views/admin/stage/insert.blade.php
@extends("admin.app")

@section('css')
    <link rel="stylesheet" href="{{ asset("admin/summernote/summernote-bs4.css") }}">
@endsection

@section("content")
    <div class="content">
        <div class="page-inner">
            <div class="page-header">
                <h4 class="page-title">Create New Stage</h4>
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="{{ route("admin.dashboard.index") }}">
                            <i class="flaticon-home"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow"></i>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route("admin.course.index") }}">Data</a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow"></i>
                    </li>
                    <li class="nav-item">
                        <a href="#">Create Data</a>
                    </li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route("admin.stage.store") }}" method="POST">
                                @csrf
                                <input type="hidden" name="course_id" value="{{ $course_id }}">
                                <div class="form-group @error(" title") has-error has-feedback @enderror">
                                    <label for="title">Course Title</label>
                                    <input type="text" class="form-control" name="title" value="{{ old("title") }}"
                                           id="title"
                                           placeholder="Title">
                                    @error("title")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group @error(" content") has-error has-feedback @enderror">
                                    <label for="cotent">Content</label>
                                    <textarea name="content" id="content-text" rows="10">{{ old("content") }}</textarea>
                                    @error("content")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group @error(" video") has-error has-feedback @enderror">
                                    <label for="video">URL Video Embed</label>
                                    <input type="text" class="form-control" name="video" value="{{ old("video") }}"
                                           id="video"
                                           placeholder="video">
                                    @error("video")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Sumbit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('js')
    <script src="{{ asset("admin/summernote/summernote-bs4.js") }}"></script>
    <script>
        $(document).ready(function () {
            $('#content-text').summernote({
                height: 300,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ],
                callbacks: {
                    onImageUpload: function(image) {
                        uploadImage(image[0]);
                    },
                    onMediaDelete : function(target) {
                        deleteImage(target[0].src);
                    }
                }
            });
        });

        function uploadImage(image) {
            var data = new FormData();
            data.append("file", image);
            $.ajax({
                url: `{{ route("image.upload") }}`,
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "POST",
                success: function(url) {
                    $('#content-text').summernote("insertImage", url);
                },
                error: function(data) {
                    console.log(data);
                }
            });
        }

        function deleteImage(src) {
            $.ajax({
                data: {src : src},
                type: "POST",
                url: `{{ route("image.delete") }}`,
                cache: false,
                success: function(response) {
                    console.log(response);
                }
            });
        }
    </script>
@endsection

resources/views/admin/stage/update.blade.php
@extends("admin.app")

@section('css')
    <link rel="stylesheet" href="{{ asset("admin/summernote/summernote-bs4.css") }}">
@endsection

@section("content")
    <div class="content">
        <div class="page-inner">
            <div class="page-header">
                <h4 class="page-title">Update Content Stage</h4>
                <ul class="breadcrumbs">
                    <li class="nav-home">
                        <a href="{{ route("admin.dashboard.index") }}">
                            <i class="flaticon-home"></i>
                        </a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow"></i>
                    </li>
                    <li class="nav-item">
                        <a href="{{ route("admin.course.index") }}">Data</a>
                    </li>
                    <li class="separator">
                        <i class="flaticon-right-arrow"></i>
                    </li>
                    <li class="nav-item">
                        <a href="#">Update Data</a>
                    </li>
                </ul>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="{{ route("admin.stage.update",['id' => $stage->id]) }}" method="POST">
                                @csrf
                                <input type="hidden" name="course_id" value="{{ $stage->course_id }}">
                                <div class="form-group @error(" title") has-error has-feedback @enderror">
                                    <label for="title">Course Title</label>
                                    <input type="text" class="form-control" name="title"
                                           value="{{ $stage->title ?? old("title") }}"
                                           id="title" placeholder="Title">
                                    @error("title")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group @error(" content") has-error has-feedback @enderror">
                                    <label for="cotent">Content</label>
                                    <textarea name="content" id="content-text"
                                              rows="10">{{$stage->content ?? old("content") }}</textarea>
                                    @error("content")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group @error(" video") has-error has-feedback @enderror">
                                    <label for="video">URL Video Embed</label>
                                    <input type="text" class="form-control" name="video"
                                           value="{{$stage->video ?? old("video") }}"
                                           id="video" placeholder="video">
                                    @error("video")
                                    <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <button class="btn btn-primary" type="submit">Sumbit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('js')
    <script src="{{ asset("admin/summernote/summernote-bs4.js") }}"></script>
    <script>
        $(document).ready(function () {
            $('#content-text').summernote({
                height: 300,
                toolbar: [
                    ['style', ['style']],
                    ['font', ['bold', 'underline', 'clear']],
                    ['color', ['color']],
                    ['para', ['ul', 'ol', 'paragraph']],
                    ['table', ['table']],
                    ['insert', ['link', 'picture', 'video']],
                    ['view', ['fullscreen', 'codeview', 'help']]
                ],
                callbacks: {
                    onImageUpload: function (image) {
                        uploadImage(image[0]);
                    },
                    onMediaDelete: function (target) {
                        deleteImage(target[0].src);
                    }
                }
            });
        });

        function uploadImage(image) {
            var data = new FormData();
            data.append("file", image);
            $.ajax({
                url: `{{ route("image.upload") }}`,
                cache: false,
                contentType: false,
                processData: false,
                data: data,
                type: "POST",
                success: function (url) {
                    $('#content-text').summernote("insertImage", url);
                },
                error: function (data) {
                    console.log(data);
                }
            });
        }

        function deleteImage(src) {
            $.ajax({
                data: {src: src},
                type: "POST",
                url: `{{ route("image.delete") }}`,
                cache: false,
                success: function (response) {
                    console.log(response);
                }
            });
        }
    </script>
@endsection