routes/admin.php
<?php

// use Illuminate\Support\Facades\Route;

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::view("/test", 'test' );
Route::view('/sertifikat', 'user.sertifikat');
    Route::view('/', 'landing')->middleware("guest");
Route::group(['namespace' => "User\Auth", "middleware" => "guest", "as" => "user."], function () {
    Route::get("/login", "AuthController@showLogin")->name("login");
    Route::post("/login", "AuthController@login")->name("login.proses");
    Route::get("/register", "AuthController@showRegister")->name("register");
    Route::post("/register", "AuthController@register")->name("register.proses");
});

Route::group(['namespace' => "User", "middleware" => "auth:web", "as" => "user."], function () {
    Route::get("/logout", "Auth\AuthController@logout")->name("logout");
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");
    /**
     * Route User Course
     */
    Route::get("/course", "CourseController@index")->name("course.index");
    Route::get("/course/{courseId}", "CourseController@show")->name("course.show");
    Route::get("/course/{courseId}/done", "CourseController@updateCourseIsDone")->name("course.done");

    /**
     *  Route for Quiz
     */
    Route::get("/course/{courseId}/quiz/", "QuizController@index")->name("quiz.index");
    Route::post("/course/{courseId}/quiz/submit", "QuizController@submit")->name("quiz.submit");

    /**
     *  Route for Mission
     */

    Route::get("/mission", "MissionController@index")->name("mission.index");
    Route::get("/mission/{id}", "MissionController@show")->name("mission.show");
    Route::post("/mission/success", "MissionController@takeMission")->name("mission.take");

    Route::get("/leaderboard", "LeaderboardController@index")->name("leaderboard.index");
    Route::get("/certificate", "DashboardController@certificate")->name('certificate');
});




/**
 * This is route for admin page
 */
Route::redirect('admin', 'admin/dashboard');
Route::prefix('admin')->group(function () {
    Route::group(['namespace' => "Admin\Auth", "middleware" => "guest:admin", "as" => "admin."], function () {
        Route::get("/login", "AuthController@showLogin")->name("login");
        Route::post("/login", "AuthController@login")->name("login.proses");
        Route::get("/register", "AuthController@showRegister")->name("register");
        Route::post("/register", "AuthController@register")->name("register.proses");
    });

    Route::group(['namespace' => "Admin", "middleware" => "auth:admin", "as" => "admin."], function () {
        Route::get("/logout", "Auth\AuthController@logout")->name("logout");
        Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

        /**
         * Route Courses Page
         */
        Route::get("/course", "CourseController@index")->name("course.index");
        Route::get("/course/create", "CourseController@create")->name("course.create");
        Route::post("/course/store", "CourseController@store")->name("course.store");
        Route::get("/course/{id}/show", "CourseController@show")->name("course.show");
        Route::get("/course/{id}/edit", "CourseController@edit")->name("course.edit");
        Route::post("/course/{id}/update", "CourseController@update")->name("course.update");
        Route::get("/course/{id}/delete", "CourseController@delete")->name("course.delete");

        /**
         * Route for Stage
         */
        Route::get("/course/stage/create/{course_id}", "StageController@create")->name("stage.create");
        Route::post("/course/stage/store", "StageController@store")->name("stage.store");
        Route::get("/course/stage/{id}/edit", "StageController@edit")->name("stage.edit");
        Route::post("/course/stage/{id}/update", "StageController@update")->name("stage.update");
        Route::get("/course/stage/{id}/delete", "StageController@delete")->name("stage.delete");

        /**
         * Route for Quiz
         */
        Route::get("/course/quiz/create/{course_id}", "QuizController@create")->name("quiz.create");
        Route::post("/course/quiz/store", "QuizController@store")->name("quiz.store");
        Route::get("/course/quiz/{id}/edit", "QuizController@edit")->name("quiz.edit");
        Route::post("/course/quiz/{id}/update", "QuizController@update")->name("quiz.update");
        Route::get("/course/quiz/{id}/delete", "QuizController@delete")->name("quiz.delete");

        /**
         * Route for Mission
         */
        Route::get("/mission", "MissionController@index")->name("mission.index");
        Route::get("/mission/create", "MissionController@create")->name("mission.create");
        Route::post("/mission/store", "MissionController@store")->name("mission.store");
        Route::get("/mission/{id}/edit", "MissionController@edit")->name("mission.edit");
        Route::post("/mission/{id}/update", "MissionController@update")->name("mission.update");
        Route::get("/mission/{id}/delete", "MissionController@delete")->name("mission.delete");
        Route::get("/mission/{id}/show", "MissionController@show")->name("mission.show");
    });
});

/**
 *  Route for image upload
 */

app/Models/Quiz.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Quiz extends Model
{
    protected $guarded = [];

    public function scopeQuestion($query, $courseId)
    {
        return $query->where("course_id", $courseId);
    }
}

app/Http/Controllers/Admin/QuizController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Quiz\QuizStoreRequest;
use App\Models\Quiz;
use Illuminate\Http\Request;

class QuizController extends BaseAdminController
{
    public function create($course_id)
    {
        return view("admin.quiz.insert", compact('course_id'));
    }

    public function edit($id)
    {
        $quiz = Quiz::find($id);
        return view("admin.quiz.update", compact('quiz'));
    }

    public function store(QuizStoreRequest $request)
    {
        $data = $request->validated();
        $quizStore = Quiz::create($data);
        if (!$quizStore) {
            $this->setNotifyMessage("failed", "Create data failed!");
            return redirect()->back()->withInput();
        }
        $this->setNotifyMessage("success", "Create data success!");
        return redirect()->route("admin.course.show", ["id" => $request->course_id]);
    }

    public function update(QuizStoreRequest $request, $id)
    {
        $data = $request->validated();
        $quiz = Quiz::find($id)->update($data);
        if (!$quiz) {
            $this->setNotifyMessage("failed", "Update data failed!");
            return redirect()->back()->withInput();
        }
        $this->setNotifyMessage("success", "Update data success!");
        return redirect()->route("admin.course.show", ["id" => $request->course_id]);
    }

    public function delete($id)
    {
        $quiz = Quiz::find($id);
        $course_id = $quiz->course_id;
        $quiz->delete();
        if (!$quiz) {
            $this->setNotifyMessage("failed", "Delete data failed!");
            return redirect()->route("admin.course.show", ["id" => $course_id]);
        }
        $this->setNotifyMessage("success", "Delete data success!");
        return redirect()->route("admin.course.show", ["id" => $course_id]);
    }
}

app/Http/Controllers/User/QuizController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Quiz;
use App\Repositories\Course\CourseRepository;
use App\Repositories\Quiz\QuizRepository;
use Illuminate\Http\Request;

class QuizController extends BaseUserController
{
    public $minimal_score = 70;
    public $quizRepository;

    public function __construct(QuizRepository $quizRepository)
    {
        $this->quizRepository = $quizRepository;
    }

    public function index(Request $request, $courseId)
    {
        $page = $request->page;
        $quiz = $this->quizRepository->getQuizPaginate($courseId);
        $count = $this->quizRepository->amoutQuestion($courseId);
        if ($request->ajax()) {
            return view("user.quiz.question", compact("quiz", "page", "count", "courseId"))->render();
        }
        return view("user.quiz.index", compact("quiz", "page", "count", "courseId"));
    }

    public function submit(Request $request, $courseId)
    {
        $score = $this->quizRepository->getScore($request);
        if ($score >= $this->minimal_score) {
            $this->quizRepository->setNextCourse(new CourseRepository());
            $this->quizRepository->setUserPoint(auth()->user()->id, "quiz", $courseId, $score);
            $message = "Selamat anda berhasil lulus pada quiz ini, silahkan lanjut course berikutnya";
            return view("user.quiz.report", compact("score", "message"));
        }
        $message = "Sayang sekali, anda belum berhasil pada quiz ini, silahkan pelajari lagi materinya";
        return view("user.quiz.report", compact("score", "message"));
    }
}

resources/views/admin/quiz/insert.blade.php
@extends("admin.app")

@section('css')
<link rel="stylesheet" href="{{ asset("admin/summernote/summernote-bs4.css") }}">
@endsection

@section("content")
<div class="content">
  <div class="page-inner">
    <div class="page-header">
      <h4 class="page-title">Create New Quiz</h4>
      <ul class="breadcrumbs">
        <li class="nav-home">
          <a href="{{ route("admin.dashboard.index") }}">
            <i class="flaticon-home"></i>
          </a>
        </li>
        <li class="separator">
          <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
          <a href="{{ route("admin.course.index") }}">Data</a>
        </li>
        <li class="separator">
          <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
          <a href="#">Create Data</a>
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="{{ route("admin.quiz.store") }}" method="POST">
              @csrf
              <input type="hidden" name="course_id" value="{{ $course_id }}">
              <div class="form-group row @error(" question") has-error has-feedback @enderror">
                <label for="question" class="col-2">Quiz Question</label>
                <textarea name="question" class="col-10" id="question" rows="5">{{ old("question") }}</textarea>
                @error("question")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_a") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option A</label>
                <textarea name="answer_a" class="col-10" id="answer_a" rows="5">{{ old("answer_a") }}</textarea>
                @error("answer_a")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_b") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option B</label>
                <textarea name="answer_b" class="col-10" id="answer_b" rows="5">{{ old("answer_b") }}</textarea>
                @error("answer_b")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_c") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option C</label>
                <textarea name="answer_c" class="col-10" id="answer_c" rows="5">{{ old("answer_c") }}</textarea>
                @error("answer_c")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_d") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option D</label>
                <textarea name="answer_d" class="col-10" id="answer_d" rows="5">{{ old("answer_d") }}</textarea>
                @error("answer_d")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row">
                <label for="defaultSelect" class="col-2">Default Select</label>
                <select name="correct_answer" class="form-control form-control col-10" id="defaultSelect">
                  <option>A</option>
                  <option>B</option>
                  <option>C</option>
                  <option>D</option>
                </select>
              </div>
              <div class="form-group">
                <button class="btn btn-primary" type="submit">Sumbit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection
@section('js')
<script src="{{ asset("admin/summernote/summernote-bs4.js") }}"></script>
<script>
  $(document).ready(function() {
    $('#question').summernote({
      height: 200,
    });
    $('#answer_a').summernote({
      height: 100,
    });
    $('#answer_b').summernote({
      height: 100,
    });
    $('#answer_c').summernote({
      height: 100,
    });
    $('#answer_d').summernote({
      height: 100,
    });
  });
</script>
@endsection

resources/views/admin/quiz/update.blade.php
@extends("admin.app")

@section('css')
<link rel="stylesheet" href="{{ asset("admin/summernote/summernote-bs4.css") }}">
@endsection

@section("content")
<div class="content">
  <div class="page-inner">
    <div class="page-header">
      <h4 class="page-title">Update Data Quiz</h4>
      <ul class="breadcrumbs">
        <li class="nav-home">
          <a href="{{ route("admin.dashboard.index") }}">
            <i class="flaticon-home"></i>
          </a>
        </li>
        <li class="separator">
          <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
          <a href="{{ route("admin.course.index") }}">Data Course</a>
        </li>
        <li class="separator">
          <i class="flaticon-right-arrow"></i>
        </li>
        <li class="nav-item">
          <a href="#">Update Data</a>
        </li>
      </ul>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-body">
            <form action="{{ route("admin.quiz.update",["id" => $quiz->id]) }}" method="POST">
              @csrf
              <input type="hidden" name="course_id" value="{{ $quiz->course_id }}">
              <div class="form-group row @error(" question") has-error has-feedback @enderror">
                <label for="question" class="col-2">Quiz Question</label>
                <textarea name="question" class="col-10" id="question"
                  rows="5">{{ $quiz->question ?? old("question") }}</textarea>
                @error("question")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_a") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option A</label>
                <textarea name="answer_a" class="col-10" id="answer_a"
                  rows="5">{{ $quiz->answer_a ?? old("answer_a") }}</textarea>
                @error("answer_a")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_b") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option B</label>
                <textarea name="answer_b" class="col-10" id="answer_b"
                  rows="5">{{ $quiz->answer_b ?? old("answer_b") }}</textarea>
                @error("answer_b")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_c") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option C</label>
                <textarea name="answer_c" class="col-10" id="answer_c"
                  rows="5">{{ $quiz->answer_c ?? old("answer_c") }}</textarea>
                @error("answer_c")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row @error(" answer_d") has-error has-feedback @enderror">
                <label for="cotent" class="col-2">Option D</label>
                <textarea name="answer_d" class="col-10" id="answer_d"
                  rows="5">{{ $quiz->answer_d ?? old("answer_d") }}</textarea>
                @error("answer_d")
                <small id="emailHelp" class="form-text text-danger">{{ $message }}</small>
                @enderror
              </div>
              <div class="form-group row">
                <label for="defaultSelect" class="col-2">Default Select</label>
                <select name="correct_answer" class="form-control form-control col-10" id="defaultSelect">
                  <option @if($quiz->correct_answer == 'a') selected @endif value="a">A</option>
                  <option @if($quiz->correct_answer == 'b') selected @endif value="b">B</option>
                  <option @if($quiz->correct_answer == 'c') selected @endif value="c">C</option>
                  <option @if($quiz->correct_answer == 'd') selected @endif value="d">D</option>
                </select>
              </div>
              <div class="form-group">
                <button class="btn btn-primary" type="submit">Sumbit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection
@section('js')
<script src="{{ asset("admin/summernote/summernote-bs4.js") }}"></script>
<script>
  $(document).ready(function() {
    $('#question').summernote({
      height: 200,
    });
    $('#answer_a').summernote({
      height: 100,
    });
    $('#answer_b').summernote({
      height: 100,
    });
    $('#answer_c').summernote({
      height: 100,
    });
    $('#answer_d').summernote({
      height: 100,
    });
  });
</script>
@endsection