routes/admin.php
<?php

// use Illuminate\Support\Facades\Route;

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::view("/test", 'test' );
Route::view('/sertifikat', 'user.sertifikat');
    Route::view('/', 'landing')->middleware("guest");
Route::group(['namespace' => "User\Auth", "middleware" => "guest", "as" => "user."], function () {
    Route::get("/login", "AuthController@showLogin")->name("login");
    Route::post("/login", "AuthController@login")->name("login.proses");
    Route::get("/register", "AuthController@showRegister")->name("register");
    Route::post("/register", "AuthController@register")->name("register.proses");
});

Route::group(['namespace' => "User", "middleware" => "auth:web", "as" => "user."], function () {
    Route::get("/logout", "Auth\AuthController@logout")->name("logout");
    Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");
    /**
     * Route User Course
     */
    Route::get("/course", "CourseController@index")->name("course.index");
    Route::get("/course/{courseId}", "CourseController@show")->name("course.show");
    Route::get("/course/{courseId}/done", "CourseController@updateCourseIsDone")->name("course.done");

    /**
     *  Route for Quiz
     */
    Route::get("/course/{courseId}/quiz/", "QuizController@index")->name("quiz.index");
    Route::post("/course/{courseId}/quiz/submit", "QuizController@submit")->name("quiz.submit");

    /**
     *  Route for Mission
     */

    Route::get("/mission", "MissionController@index")->name("mission.index");
    Route::get("/mission/{id}", "MissionController@show")->name("mission.show");
    Route::post("/mission/success", "MissionController@takeMission")->name("mission.take");

    Route::get("/leaderboard", "LeaderboardController@index")->name("leaderboard.index");
    Route::get("/certificate", "DashboardController@certificate")->name('certificate');
});




/**
 * This is route for admin page
 */
Route::redirect('admin', 'admin/dashboard');
Route::prefix('admin')->group(function () {
    Route::group(['namespace' => "Admin\Auth", "middleware" => "guest:admin", "as" => "admin."], function () {
        Route::get("/login", "AuthController@showLogin")->name("login");
        Route::post("/login", "AuthController@login")->name("login.proses");
        Route::get("/register", "AuthController@showRegister")->name("register");
        Route::post("/register", "AuthController@register")->name("register.proses");
    });

    Route::group(['namespace' => "Admin", "middleware" => "auth:admin", "as" => "admin."], function () {
        Route::get("/logout", "Auth\AuthController@logout")->name("logout");
        Route::get("/dashboard", "DashboardController@index")->name("dashboard.index");

        /**
         * Route Courses Page
         */
        Route::get("/course", "CourseController@index")->name("course.index");
        Route::get("/course/create", "CourseController@create")->name("course.create");
        Route::post("/course/store", "CourseController@store")->name("course.store");
        Route::get("/course/{id}/show", "CourseController@show")->name("course.show");
        Route::get("/course/{id}/edit", "CourseController@edit")->name("course.edit");
        Route::post("/course/{id}/update", "CourseController@update")->name("course.update");
        Route::get("/course/{id}/delete", "CourseController@delete")->name("course.delete");

        /**
         * Route for Stage
         */
        Route::get("/course/stage/create/{course_id}", "StageController@create")->name("stage.create");
        Route::post("/course/stage/store", "StageController@store")->name("stage.store");
        Route::get("/course/stage/{id}/edit", "StageController@edit")->name("stage.edit");
        Route::post("/course/stage/{id}/update", "StageController@update")->name("stage.update");
        Route::get("/course/stage/{id}/delete", "StageController@delete")->name("stage.delete");

        /**
         * Route for Quiz
         */
        Route::get("/course/quiz/create/{course_id}", "QuizController@create")->name("quiz.create");
        Route::post("/course/quiz/store", "QuizController@store")->name("quiz.store");
        Route::get("/course/quiz/{id}/edit", "QuizController@edit")->name("quiz.edit");
        Route::post("/course/quiz/{id}/update", "QuizController@update")->name("quiz.update");
        Route::get("/course/quiz/{id}/delete", "QuizController@delete")->name("quiz.delete");

        /**
         * Route for Mission
         */
        Route::get("/mission", "MissionController@index")->name("mission.index");
        Route::get("/mission/create", "MissionController@create")->name("mission.create");
        Route::post("/mission/store", "MissionController@store")->name("mission.store");
        Route::get("/mission/{id}/edit", "MissionController@edit")->name("mission.edit");
        Route::post("/mission/{id}/update", "MissionController@update")->name("mission.update");
        Route::get("/mission/{id}/delete", "MissionController@delete")->name("mission.delete");
        Route::get("/mission/{id}/show", "MissionController@show")->name("mission.show");
    });
});

/**
 *  Route for image upload
 */

resources/views/admin/partials/header.blade.php
<div class="main-header">
    <!-- Logo Header -->
    <div class="logo-header" data-background-color="blue">

        <a href="index.html" class="logo">
            {{-- <img src="../assets/img/logo.svg" alt="navbar brand" class="navbar-brand"> --}}
            <h1 class="navbar-brand text-white">GAMIFIED-OOP</h1>
        </a>
        <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class="icon-menu"></i>
            </span>
        </button>
        <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
        <div class="nav-toggle">
            <button class="btn btn-toggle toggle-sidebar">
                <i class="icon-menu"></i>
            </button>
        </div>
    </div>
    <!-- End Logo Header -->

    <!-- Navbar Header -->
    <nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">

        <div class="container-fluid">
            <div class="collapse" id="search-nav">
                <form class="navbar-left navbar-form nav-search mr-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <button type="submit" class="btn btn-search pr-1">
                                <i class="fa fa-search search-icon"></i>
                            </button>
                        </div>
                        <input type="text" placeholder="Search ..." class="form-control">
                    </div>
                </form>
            </div>
            <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                <li class="nav-item toggle-nav-search hidden-caret">
                    <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false"
                        aria-controls="search-nav">
                        <i class="fa fa-search"></i>
                    </a>
                </li>
                <li class="nav-item dropdown hidden-caret">
                    <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="avatar-sm text-white mx-3">
                            <h3>{{ auth()->user()->name }}</h3>
                        </div>
                    </a>
                    <ul class="dropdown-menu dropdown-user animated fadeIn">
                        <div class="dropdown-user-scroll scrollbar-outer">
                            <li>
                                <div class="user-box">
                                    <div class="u-text">
                                        <h4>{{ auth()->user()->name }}</h4>
                                        <p class="text-muted">
                                            <h4>{{ auth()->user()->email }}</h4>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="dropdown-divider"></div>
                                {{-- <a class="dropdown-item" href="#">My Profile</a>
                                <a class="dropdown-item" href="#">My Balance</a>
                                <a class="dropdown-item" href="#">Inbox</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Account Setting</a>
                                <div class="dropdown-divider"></div> --}}
                                <a class="dropdown-item" href="{{ route("admin.logout") }}">Logout</a>
                            </li>
                        </div>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
</div>

resources/views/admin/partials/notify.blade.php
@php
$success = session('success') ?? null;
$failed = session('failed') ?? null;
@endphp
<script>
    @if($success)
        $.notify({
            // options
            title: "Success",
            message: '{{ $success }}',
        },{
            // settings
            element: 'body',
            type: 'success',
            allow_dismiss: true,
            placement: {
                from: "top",
                align: "right"
            },
            timer: 1000,
            delay:1200,
        });
    @endif
    @if($failed)
        $.notify({
            // options
            title: "Failed",
            message: '{{ $failed }}',
        },{
            // settings
            element: 'body',
            type: 'danger',
            allow_dismiss: true,
            placement: {
                from: "top",
                align: "right"
            },
            timer: 1000,
            delay:1200,
        });
    @endif
</script>

resources/views/admin/partials/sidebar.blade.php
<!-- Sidebar -->
<div class="sidebar sidebar-style-2">
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
        <div class="sidebar-content">
            <ul class="nav nav-primary">
                <li class="nav-item {{ (request()->is('admin/dashboard')) ? 'active' : '' }}">
                    <a href="{{ route("admin.dashboard.index") }}" class="" aria-expanded="false">
                        <i class="fas fa-home"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item {{ (request()->is('admin/course*')) ? 'active' : '' }}">
                    <a href="{{ route("admin.course.index") }}" class="" aria-expanded="false">
                        <i class="fas fa-boxes"></i>
                        <p>Course</p>
                    </a>
                </li>
                <li class="nav-item {{ (request()->is('admin/mission*')) ? 'active' : '' }}">
                    <a href="{{ route("admin.mission.index") }}" class="" aria-expanded="false">
                        <i class="fas fa-trophy"></i>
                        <p>Mission</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
<!-- End Sidebar -->